version: '3'
services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=pwauser
      - POSTGRES_PASSWORD=pwakey
      - POSTGRES_DB=pwa
  app:
    image: yiisoftware/yii2-php:8.1-apache
    ports:
      - 8000:80
    volumes:
      - ./src/composer/cache:/root/.composer/cache:delegated
      - ./src/basic:/app:delegated
      - .:/var/www/html
    depends_on:
      - db